import React, { useMemo, useState } from 'react';
import { FlatList, Image, ScrollView, StyleSheet, Text, View } from 'react-native';
import { NativeStackScreenProps } from '@react-navigation/native-stack';
import { AppButton, AppHeader, EmptyState, Field, FilterChip, InfoRow, PriceSummary, PromoBanner, ReservationTicket, VehicleCard } from '../components/ui';
import { vehicles } from '../data/vehicles';
import { theme } from '../theme/theme';
import { RootStackParamList } from '../navigation/RootNavigator';
import { MileageMode, VehicleCategory } from '../types';

export const LoginScreen = ({ onLogin }: any) => { const [email,setEmail]=useState(''); const [pass,setPass]=useState(''); return <View style={s.container}><AppHeader title="Cuencana Rent a Car" subtitle="Reserva premium en minutos"/><Field placeholder="Correo" value={email} onChangeText={setEmail}/><Field placeholder="Contraseña" value={pass} onChangeText={setPass}/><AppButton label="Ingresar" onPress={onLogin}/></View>;};
export const HomeScreen = ({ navigation }: any) => <ScrollView style={s.container}><AppHeader title="Bienvenido" subtitle="Tu vehículo listo al llegar a Cuenca"/><PromoBanner/><AppButton label="Cotizar ahora" onPress={()=>navigation.navigate('Catálogo')}/><View style={{height:10}}/><AppButton label="Soporte 24/7" variant="ghost" onPress={()=>navigation.navigate('Soporte')}/></ScrollView>;
export const CatalogScreen = ({ navigation }: any) => { const [cat,setCat]=useState<VehicleCategory|'Todos'>('Todos'); const cats:['Todos',...VehicleCategory[]]=['Todos','SUV','Sedán','Pickup','Compacto','Premium']; const filtered=useMemo(()=>cat==='Todos'?vehicles:vehicles.filter(v=>v.categoria===cat),[cat]); return <View style={s.container}><AppHeader title="Catálogo" subtitle="Selecciona el vehículo ideal"/><ScrollView horizontal showsHorizontalScrollIndicator={false} style={{marginBottom:14}}>{cats.map(c=><FilterChip key={c} label={c} active={cat===c} onPress={()=>setCat(c)}/>)}</ScrollView><FlatList data={filtered} keyExtractor={i=>i.id} renderItem={({item})=><VehicleCard item={item} onPress={()=>navigation.getParent()?.navigate('Detail',{vehicle:item})}/>} /></View>; };
export const VehicleDetailScreen = ({ route, navigation }: NativeStackScreenProps<RootStackParamList,'Detail'>) => { const {vehicle}=route.params; return <ScrollView style={s.container}><Image source={{uri:vehicle.imagen}} style={s.hero}/><AppHeader title={vehicle.nombre} subtitle={vehicle.descripcionCorta}/><InfoRow label="Año" value={`${vehicle.anio}`}/><InfoRow label="Transmisión" value={vehicle.transmision}/><InfoRow label="Asientos" value={`${vehicle.asientos}`}/><InfoRow label="Motor" value={vehicle.motor}/><InfoRow label="Tracción" value={vehicle.traccion}/><AppButton label="Cotizar" onPress={()=>navigation.navigate('Quote',{vehicle})}/></ScrollView>;};
export const QuoteScreen = ({ route, navigation }: NativeStackScreenProps<RootStackParamList,'Quote'>) => { const {vehicle}=route.params; const [days]=useState(3); const [mode,setMode]=useState<MileageMode>('libre'); const base=(mode==='libre'?vehicle.kilometrajeLibrePrecio:vehicle.kilometrajeControladoPrecio)*days; const iva=base*0.15; const total=base+iva; return <ScrollView style={s.container}><AppHeader title="Cotización" subtitle={vehicle.disponible?'Disponible para tus fechas':'No disponible para tus fechas'}/><Text style={s.muted}>Fechas mock: 20 May - 23 May (3 días)</Text><View style={{flexDirection:'row',marginVertical:10}}><FilterChip label="Kilometraje libre" active={mode==='libre'} onPress={()=>setMode('libre')}/><FilterChip label="Kilometraje controlado" active={mode==='controlado'} onPress={()=>setMode('controlado')}/></View><PriceSummary base={base} iva={iva} total={total}/>{vehicle.disponible?<AppButton label="Continuar a pago" onPress={()=>navigation.navigate('Payment',{vehicle,total,days,mode})}/>:<EmptyState title="Sin disponibilidad" desc="Elige otro vehículo o cambia fechas."/>}</ScrollView>;};
export const PaymentScreen = ({ route, navigation }: NativeStackScreenProps<RootStackParamList,'Payment'>) => { const {vehicle,total,days,mode}=route.params; const [name,setName]=useState(''); return <ScrollView style={s.container}><AppHeader title="Pago" subtitle="No se realiza cobro real en este prototipo"/><InfoRow label="Vehículo" value={vehicle.nombre}/><InfoRow label="Días" value={`${days}`}/><InfoRow label="Plan" value={mode}/><InfoRow label="Total" value={`$${total.toFixed(2)}`}/><Field placeholder="Nombre completo" value={name} onChangeText={setName}/><Field placeholder="Documento" value={''} onChangeText={()=>{}}/><Field placeholder="Email" value={''} onChangeText={()=>{}}/><AppButton label="Confirmar reserva" onPress={()=>navigation.navigate('Confirmation',{code:`CRC-${Math.floor(Math.random()*90000)+10000}`,total})}/></ScrollView>;};
export const ConfirmationScreen = ({ route, navigation }: NativeStackScreenProps<RootStackParamList,'Confirmation'>) => <ScrollView style={s.container}><AppHeader title="¡Reserva confirmada!" subtitle="Contrato y firma presencial al retirar el vehículo"/><ReservationTicket code={route.params.code} total={route.params.total}/><View style={{height:12}}/><AppButton label="Ir al soporte" variant="secondary" onPress={()=>navigation.navigate('Main')}/></ScrollView>;
export const HistoryScreen = () => <View style={s.container}><AppHeader title="Historial" subtitle="Tus reservas anteriores"/><View style={styles.item}><Text style={s.bold}>CRC-18442</Text><Text style={s.muted}>Toyota Corolla · Completada · $203.55</Text></View><View style={styles.item}><Text style={s.bold}>CRC-12298</Text><Text style={s.muted}>Mazda CX-5 · Confirmada · $358.80</Text></View></View>;
export const SupportScreen = () => <View style={s.container}><AppHeader title="Soporte" subtitle="Asistencia inmediata"/><InfoRow label="WhatsApp" value="+593 99 000 0000"/><InfoRow label="Emergencias" value="+593 99 111 1111"/><InfoRow label="Aseguradora" value="Seguros Andinos"/><Text style={s.muted}>FAQ: cambios de fecha, cobertura y políticas.</Text></View>;

const s=StyleSheet.create({container:{flex:1,backgroundColor:theme.colors.background,padding:16},hero:{width:'100%',height:220,borderRadius:18,marginBottom:12},muted:{color:theme.colors.textMuted},bold:{fontWeight:'700'}});
const styles=StyleSheet.create({item:{backgroundColor:'#fff',padding:14,borderRadius:16,marginBottom:10}});
