import React from 'react';
import { Image, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { theme } from '../theme/theme';
import { Vehicle } from '../types';

export const AppButton = ({ label, onPress, variant='primary' }: { label: string; onPress: () => void; variant?: 'primary'|'secondary'|'ghost' }) => (
  <Pressable onPress={onPress} style={[styles.btn, variant === 'secondary' && styles.btnSecondary, variant === 'ghost' && styles.btnGhost]}><Text style={[styles.btnText, variant!=='primary' && {color: theme.colors.text}]}>{label}</Text></Pressable>
);
export const AppHeader = ({ title, subtitle }: { title: string; subtitle?: string }) => <View style={{marginBottom: theme.spacing.md}}><Text style={styles.h1}>{title}</Text>{subtitle ? <Text style={styles.muted}>{subtitle}</Text> : null}</View>;
export const PromoBanner = () => <View style={styles.banner}><Text style={styles.bannerTag}>Oferta limitada</Text><Text style={styles.bannerTitle}>15% off en reservas de 5+ días</Text><Text style={styles.muted}>Retiro prioritario en Cuenca aeropuerto.</Text></View>;
export const FilterChip = ({label,active,onPress}:{label:string;active:boolean;onPress:()=>void}) => <Pressable onPress={onPress} style={[styles.chip, active && styles.chipActive]}><Text style={[styles.chipText, active && {color:'#fff'}]}>{label}</Text></Pressable>;
export const VehicleCard = ({item,onPress}:{item:Vehicle;onPress:()=>void}) => <Pressable onPress={onPress} style={styles.card}><Image source={{uri:item.imagen}} style={styles.vehicleImage}/><View style={{padding:14}}><Text style={styles.h3}>{item.nombre}</Text><Text style={styles.muted}>{item.categoria} · {item.transmision}</Text><Text style={styles.price}>Desde ${item.kilometrajeControladoPrecio}/día</Text></View></Pressable>;
export const InfoRow = ({label,value}:{label:string;value:string}) => <View style={styles.row}><Text style={styles.muted}>{label}</Text><Text style={{fontWeight:'600'}}>{value}</Text></View>;
export const PriceSummary = ({base,iva,total}:{base:number;iva:number;total:number}) => <View style={styles.summary}><InfoRow label="Tarifa" value={`$${base.toFixed(2)}`}/><InfoRow label="IVA incluido" value={`$${iva.toFixed(2)}`}/><InfoRow label="Sin cargos ocultos" value="Sí"/><View style={styles.row}><Text style={styles.h3}>Total</Text><Text style={styles.h3}>${total.toFixed(2)}</Text></View></View>;
export const ReservationTicket = ({code,total}:{code:string;total:number}) => <View style={styles.ticket}><Ionicons name="qr-code-outline" size={56} color={theme.colors.secondary}/><Text style={styles.h3}>Reserva #{code}</Text><Text style={styles.muted}>Total pagado ${total.toFixed(2)}</Text></View>;
export const EmptyState = ({title,desc}:{title:string;desc:string}) => <View style={{padding:28,alignItems:'center'}}><Ionicons name="car-outline" size={42} color={theme.colors.textMuted}/><Text style={styles.h3}>{title}</Text><Text style={[styles.muted,{textAlign:'center'}]}>{desc}</Text></View>;
export const Field = ({placeholder,value,onChangeText}:{placeholder:string;value:string;onChangeText:(t:string)=>void}) => <TextInput style={styles.input} placeholder={placeholder} placeholderTextColor={theme.colors.textMuted} value={value} onChangeText={onChangeText}/>;

const styles=StyleSheet.create({h1:{...theme.typography.h1,color:theme.colors.text},h3:{...theme.typography.h3,color:theme.colors.text},muted:{color:theme.colors.textMuted,marginTop:4},btn:{backgroundColor:theme.colors.primary,padding:14,borderRadius:theme.radii.md,alignItems:'center'},btnSecondary:{backgroundColor:theme.colors.secondary},btnGhost:{backgroundColor:theme.colors.chipBg},btnText:{color:'#fff',fontWeight:'700'},banner:{backgroundColor:'#fff',padding:18,borderRadius:theme.radii.lg,...theme.shadows.card,marginBottom:16},bannerTag:{color:theme.colors.primary,fontWeight:'700'},bannerTitle:{fontSize:18,fontWeight:'700',marginVertical:6},chip:{paddingHorizontal:14,paddingVertical:8,borderRadius:theme.radii.pill,backgroundColor:theme.colors.chipBg,marginRight:8},chipActive:{backgroundColor:theme.colors.secondary},chipText:{fontWeight:'600'},card:{backgroundColor:'#fff',borderRadius:theme.radii.lg,overflow:'hidden',marginBottom:16,...theme.shadows.card},vehicleImage:{width:'100%',height:180},price:{marginTop:8,fontWeight:'700',fontSize:18,color:theme.colors.secondary},row:{flexDirection:'row',justifyContent:'space-between',marginVertical:5},summary:{backgroundColor:'#fff',borderRadius:theme.radii.lg,padding:16},ticket:{padding:20,alignItems:'center',backgroundColor:'#fff',borderRadius:theme.radii.lg},input:{backgroundColor:'#fff',padding:14,borderRadius:theme.radii.md,borderWidth:1,borderColor:theme.colors.border,marginBottom:10}});
